<?php
require_once('assets/includes/helper.php');
$app_api_not_type   = 'Type not found';
$error_code_1 = 1;
$error_code_2 = 2;
$error_code_3 = 3;
$error_code_4 = 4;
$error_code_5 = 5;
$error_code_6 = 6;
$error_code_7 = 7;
$api_status_errors_404      = 404;
$api_status_errors_400      = 400;
$api_status_success_200     = 200;
$check_out_type = [ 'pro','wallet', 'fund'];
$arr_pro_type = [1, 2, 3, 4];
$app_api_applications = [ 'phone','windows_app'];
$auto_pages = [
    'general-settings',
    'dashboard',
    'site-settings',
    'dashboard',
    'site-features',
    'amazon-settings',
    'email-settings',
    'social-login',
    'video-settings',
    'manage-languages',
    'add-language',
    'edit-lang',
    'manage-users',
    'manage-stories',
    'manage-profile-fields',
    'add-new-profile-field',
    'edit-profile-field',
    'manage-verification-reqeusts',
    'payment-reqeuests',
    'affiliates-settings',
    'referrals-list',
    'pro-memebers',
    'pro-settings',
    'pro-payments',
    'payment-settings',
    'manage-pages',
    'manage-groups',
    'manage-posts',
    'manage-articles',
    'manage-events',
    'manage-forum-sections',
    'manage-forum-forums',
    'manage-forum-threads',
    'manage-forum-messages',
    'create-new-section',
    'create-new-forum',
    'manage-movies',
    'add-new-movies',
    'manage-games',
    'add-new-game',
    'ads-settings',
    'manage-site-ads',
    'manage-user-ads',
    'manage-themes',
    'manage-site-design',
    'manage-announcements',
    'mass-notifications',
    'ban-users',
    'generate-sitemap',
    'manage-invitation-keys',
    'backups',
    'manage-custom-pages',
    'add-new-custom-page',
    'edit-custom-page',
    'edit-terms-pages',
    'manage_terms_pages',
    'manage-reports',
    'push-notifications-system',
    'manage-api-access-keys',
    'verfiy-applications',
    'manage-updates',
    'changelog',
    'online-users',
    'custom-code',
    'manage-third-psites',
    'edit-movie',
    'auto-delete',
    'manage-gifts',
    'add-new-gift',
    'post-settings',
    'manage-stickers',
    'add-new-sticker',
    'manage-apps',
    'auto-friend',
    'fake-users',
    'manage-genders',
    'pages-categories',
    'groups-categories',
    'blogs-categories',
    'products-categories',
    'bank-receipts',
    'manage-currencies',
    'manage-colored-posts',
    'job-categories',
    'manage-fund',
    'manage-jobs',
    'auto-like',
    'auto-join',
    'manage-reactions',
    'pages-sub-categories',
    'groups-sub-categories',
    'products-sub-categories',
    'pages-fields',
    'groups-fields',
    'products-fields',
    'pro-features',
    'pro-refund',
    'manage-offers',
    'manage-invitation',
    'send_email',
    'live',
    'node',
    'manage_emails',
    'ffmpeg',
    'manage-permissions',
    'store-settings',
    'manage-products',
    'manage-orders',
    'manage-reviews',
    'website_mode',
    'user_reports',
    'edit-forum',
    'edit-section',
    'cronjob_settings',
    'system_status',
    "upload-to-storage",
    "ai-settings",
    "manage-content-monetization",
];
$wo_mod_pages = [
    'dashboard',
    'post-settings',
    'manage-stickers',
    'manage-gifts',
    'manage-users',
    'online-users',
    'manage-stories',
    'manage-pages',
    'manage-groups',
    'manage-posts',
    'manage-articles',
    'manage-events',
    'manage-forum-threads',
    'manage-forum-messages',
    'manage-movies',
    'manage-games',
    'add-new-game',
    'manage-user-ads',
    'manage-reports',
    'manage-third-psites',
    'edit-movie',
    'bank-receipts',
    'job-categories',
    'manage-jobs'
];
$request_allow_array = [
    'upgrade',
    'paystack',
    'cashfree',
    'payment',
    'pay_with_bitcoin',
    'coinpayments_callback',
    'paypro_with_bitcoin',
    'upload-blog-image',
    'wallet',
    'download_user_info',
    'movies',
    'funding',
    'stripe',
    'coinbase',
    'load_more_products',
    'yoomoney',
    'iyzipay',
    'fluttewave',
    'fortumo',
    'aamarpay',
    'pay_with_bitcoin',
];
$request_non_login_array = [
    'session_status',
    'open_lightbox',
    'get_welcome_users',
    'load_posts',
    'save_user_location',
    'load-more-groups',
    'load-more-pages',
    'load-more-users',
    'load_profile_posts',
    'confirm_user_unusal_login',
    'confirm_user',
    'confirm_sms_user',
    'resned_code',
    'resned_code_ac',
    'resned_ac_email',
    'contact_us',
    'google_login',
    'login',
    'register',
    'recover',
    'recoversms',
    'reset_password',
    'search',
    'get_search_filter',
    'update_announcement_views',
    'get_more_hashtag_posts',
    'open_album_lightbox',
    'get_next_album_image',
    'get_previous_album_image',
    'get_next_product_image',
    'get_previous_product_image',
    'open_multilightbox',
    'get_next_image',
    'get_previous_image',
    'get_next_video',
    'get_previous_video',
    'load-blogs',
    'load-recent-blogs',
    'get_no_posts_name',
    'search-blog-read',
    'search-blog',
    'coinbase',
    'load_more_products',
    'yoomoney',
    'iyzipay',
    'fluttewave',
    'fortumo',
    'aamarpay',
    'pay_with_bitcoin',
    'resend_two_factor',
    'cashfree',
];
$login_with_types = [
    'Google',
    'Facebook',
    'Twitter',
    'LinkedIn',
    'Vkontakte',
    'Instagram',
    'QQ',
    'WeChat',
    'Discord',
    'Mailru',
    'OkRu',
    'TikTok',
    'WordPress'
];
$base64_decode      = base64_decode('I2FhYQ==');
$base64_decode_za   = base64_decode('I2RkZA==');
$content_types      = "Content-type: application/json";
$msg_error_token    = "Invalid or Unauthorized token";
$app_api_non_allow  = [
    'password',
    'background_image_status',
    'email_code',
    'type',
    'start_up',
    'start_up_info',
    'startup_follow',
    'startup_image',
    'id',
    'cover_full',
    'cover_org',
    'avatar_org',
    'app_session',
    'last_email_sent',
    'sms_code',
    'pro_time',
    'css_file',
    'src',
    'followers_data',
    'following_data',
    'likes_data',
    'album_data',
    'groups_data',
    'sidebar_data',
    'showlastseen',
    'joined',
    'social_login',
];
$admin_sidebar_key = [
    "dashboard"             =>  "dashboard",
    "setting"               =>  "setting",
    "website_mode"          =>  "website_mode", // Chưa cài đặt
    "general_setting"       =>  "general_setting",
    "site_setting"          =>  "site_setting",
    "amazon_setting"        =>  "amazon_setting",
    "email_setting"         =>  "email_setting",
    "video_setting"         =>  "video_setting",
];
$admin_sidebar_default = [
    "dashboard"                 =>  "Bảng điều khiển",
    "setting"                   =>  "Thiết lập",
    "website_mode"              =>  "Chế độ trang web", // Chưa cài đặt
    "general_setting"           =>  "Cài đặt chung",
    "site_setting"              =>  "Thiết lập trang website",
    "amazon_setting"            =>  "Thiết lập amazon",
    "email_setting"             =>  "Thiết lập email",
    "video_setting"             =>  "Thiết lập video",
    "site_information"          =>  "Thông tin trang website",
    "file_upload_config"        =>  "Cấu hình tải tệp lên",
    "email_sms_setup"           =>  "Cài đặt email và SMS",
    "chat_video_audio"          =>  "Trò chuyện Video, Âm thanh",
    "social_login_setting"      =>  "Cài đặt mạng xã hội",
    "nodejs_setting"            =>  "Cài đặt Nodejs",
    "cronjob_setting"           =>  "Cài đặt CronJob",
    "ai_settings"               =>  "Cài đặt AI",
    "posts_setting"             =>  "Cài đặt bài viết",
    "manage_colored_posts"      =>  "Cài đặt bài đăng có màu",
    "post_reactions"            =>  "Phản ứng bài đăng",
    "setup_live_streaming"      =>  "Cài đặt phát trực tiếp",
    "manage_features"           =>  "Quản lý tính năng",
    "enable_disable_features"   =>  "Bật/ Tắt tính năng",
    "apps"                      =>  "Ứng dụng",
    "pages"                     =>  "Trang",
    "groups"                    =>  "Nhóm",
    "posts"                     =>  "Bài đăng",
    "funding"                   =>  "Kinh phí",
    "jobs"                      =>  "Công việc",
    "offers"                    =>  "Ưu đãi",
    "articles"                  =>  "Bài viết",
    "events"                    =>  "Sự kiện",
    "store"                     =>  "Cửa hàng",
    "store_settings"            =>  "Cài đặt cửa hàng",
    "manage_product"            =>  "Quản lý sản phẩm",
    "manage_orders"             =>  "Quản lý đơn hàng",
    "manage_review"             =>  "Quản lý đánh giá",
    "forums"                    =>  "Diễn đàn",
    "manage_forum_sec"          =>  "Quản lý phần diễn đàn",
    "manage_forums"             =>  "Quản lý diễn đàn",
    "threads"                   =>  "Chủ đề",
    "manage_threads"            =>  "Quản lý chủ đề",
    "replies"                   =>  "Trả lời",
    "manage_replies"            =>  "Quản lý trả lời",
    "create_new_seciton"        =>  "Tạo phần mới",
    "create_new_forum"          =>  "Tạo mới diễn đàn",
    "movies"                    =>  "Phim",
    "manage_movies"             =>  "Quản lý danh sách phim",
    "add_new_movies"            =>  "Tạo phim mới",
    "games"                     =>  "Trò chơi" , 
    "manage_game"               =>  "Quản lý trò chơi",
    "create_new_game"           =>  "Tạo trò chơi mới"  ,
    "categories"                =>  "Hạng mục",
    "page_categories"           =>  "Hạng mục trang",
    "page_sub_cate"             =>  "Hạng mục phụ của trang",
    "groups_categories"         =>  "Nhóm hạng mục",
    "grp_sub_categories"        =>  "Nhóm Hạng mục con",
    "blogs_categories"          =>  "Hạng mục Blogs",
    "products_categories"       =>  "Hạng mục các sản phẩm",
    "prd_sub_categories"        =>  "Hạng mục con sản phẩm",
    "job_categories"            =>  "Hạng mục công việc",
    "gifts"                     =>  "Quà tặng",
    "manage_gifts"              =>  "Quản lý quà tặng",
    "add_new_gifts"             =>  "Thêm mới quà tặng",
    "stickers"                  =>  "Hình dán",
    "manage_sticker"            =>  "Quản lý hình dán",
    "add_new_sticker"           =>  "Thêm mới hình dán",
    "custom_fields"             =>  "Trường tùy chỉnh",
    "custom_user_fields"        =>  "Tùy chỉnh người dùng",
    "custom_pages_fields"       =>  "Tùy chỉnh trang",
    "custom_group_fields"       =>  "Tùy chỉnh nhóm",
    "custom_product_fields"     =>  "Tùy chỉnh sản phẩm",
    "languages"                 =>  "Ngôn ngữ",
    "add_lang_key"              =>  "Thêm ngôn ngữ và khóa mới",
    "manage_languages"          =>  "Quản lý ngôn ngữ",
    "users"                     =>  "Người dùng",
    "manage_users"              =>  "Quản lý người dùng",
    "online_users"              =>  "Người dùng trực tuyến",
    "m_store_users_status"      =>  "Quản lý câu chuyện người dùng/ trạng thái",
    "manage"                    =>  "Quản lý",
    "manage_store"              =>  "Quản lý câu chuyện",
    "m_veri_request"            =>  "Quản lý yêu cầu xác minh ",
    "affiliate_settings"        =>  "Cài đặt liên kết",
    "affiliate_system"          =>  "Hệ thống liên kết",
    "payments"                  =>  "Thanh toán",
    "payment_request"           =>  "Yêu cầu thanh toán",
    "manage_genders"            =>  "Quản lý giới tính",
    "payments_ads"              =>  "Thanh toán và quảng cáo",
    "payment_configuration"     =>  "Cấu hình thanh toán",
    "advertisement_setting"     =>  "Cài đặt quảng cáo",
    "manage_currency"           =>  "Quản lý tiền tệ",
    "m_site_ads"                =>  "Quản lý quảng cáo trang web",
    "m_user_ads"                =>  "Quản lý quảng cáo người dùng",
    "m_bank_receipts"           =>  "Quản lý biên lai ngân hàng",
];
